---

- name: install spamhaus-droplist script
  template:
    src: templates/usr/local/sbin/spamhaus-droplist.j2
    dest: /usr/local/sbin/spamhaus-droplist
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify:
    - gather service facts
    - reload iptables
    - spamhaus-droplist
    - docker
    - docker-iptables

- name: configure spamhaus-droplist systemd service
  copy:
    src: files/etc/systemd/system/spamhaus-droplist.service
    dest: /etc/systemd/system/spamhaus-droplist.service

- name: setup spamhaus-droplist cronjob
  cron:
    name: spamhaus-droplist
    minute: '0'
    hour: '*/12'
    job: /usr/local/sbin/spamhaus-droplist >/dev/null 2>&1
    user: root
    cron_file: spamhaus-droplist
