---

- name: Install iptables-persistent
  package:
    name: iptables-persistent
    state: present

- name: Write rules.v4
  template:
    src: templates/etc/iptables/rules.v4.j2
    dest: /etc/iptables/rules.v4
  notify:
    - reload iptables
